---
driver:
  name: docker
  require_chef_omnibus: true
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 13

verifier:
  name: inspec

platforms:
  - name: debian-9
    run_list:
      - recipe[apt]
      - recipe[git]

suites:
  - name: package
    run_list:
      - recipe[dunst::package]
      - recipe[dunst::config]
  - name: compile
    run_list:
      - recipe[dunst::compile]
      - recipe[dunst::dunstify]
      - recipe[dunst::config]
    attributes:
      dunst:
        compile:
          build_dir: /opt/dunst-build
  - name: config
    run_list:
      - recipe[dunst::config]
    attributes:
      dunst:
        user: kitchen
        rules:
          my-rule:
            summary: foo
            urgency: low
          my-rule2:
            summary: bar
            urgency: critical
