---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-7.6

suites:
  - name: dunst
    run_list:
      - recipe[dunst]
    attributes:
      dunst:
        user: vagrant
        rules:
          my-rule:
            summary: foo
            urgency: low
          my-rule2:
            summary: bar
            urgency: critical
