---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-7.6

suites:
  - name: dunst
    run_list:
      - recipe[dunst]
    attributes:
      dunst:
        user: vagrant
